# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gibson.tool.v1 import tool_pb2 as gibson_dot_tool_dot_v1_dot_tool__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gibson/tool/v1/tool_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDescriptor = channel.unary_unary(
                '/gibson.tool.v1.ToolService/GetDescriptor',
                request_serializer=gibson_dot_tool_dot_v1_dot_tool__pb2.GetDescriptorRequest.SerializeToString,
                response_deserializer=gibson_dot_tool_dot_v1_dot_tool__pb2.GetDescriptorResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/gibson.tool.v1.ToolService/Execute',
                request_serializer=gibson_dot_tool_dot_v1_dot_tool__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=gibson_dot_tool_dot_v1_dot_tool__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/gibson.tool.v1.ToolService/Health',
                request_serializer=gibson_dot_tool_dot_v1_dot_tool__pb2.HealthRequest.SerializeToString,
                response_deserializer=gibson_dot_tool_dot_v1_dot_tool__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StreamExecute = channel.stream_stream(
                '/gibson.tool.v1.ToolService/StreamExecute',
                request_serializer=gibson_dot_tool_dot_v1_dot_tool__pb2.StreamExecuteRequest.SerializeToString,
                response_deserializer=gibson_dot_tool_dot_v1_dot_tool__pb2.StreamExecuteResponse.FromString,
                _registered_method=True)


class ToolServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDescriptor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamExecute(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDescriptor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDescriptor,
                    request_deserializer=gibson_dot_tool_dot_v1_dot_tool__pb2.GetDescriptorRequest.FromString,
                    response_serializer=gibson_dot_tool_dot_v1_dot_tool__pb2.GetDescriptorResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=gibson_dot_tool_dot_v1_dot_tool__pb2.ExecuteRequest.FromString,
                    response_serializer=gibson_dot_tool_dot_v1_dot_tool__pb2.ExecuteResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=gibson_dot_tool_dot_v1_dot_tool__pb2.HealthRequest.FromString,
                    response_serializer=gibson_dot_tool_dot_v1_dot_tool__pb2.HealthResponse.SerializeToString,
            ),
            'StreamExecute': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamExecute,
                    request_deserializer=gibson_dot_tool_dot_v1_dot_tool__pb2.StreamExecuteRequest.FromString,
                    response_serializer=gibson_dot_tool_dot_v1_dot_tool__pb2.StreamExecuteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gibson.tool.v1.ToolService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gibson.tool.v1.ToolService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDescriptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tool.v1.ToolService/GetDescriptor',
            gibson_dot_tool_dot_v1_dot_tool__pb2.GetDescriptorRequest.SerializeToString,
            gibson_dot_tool_dot_v1_dot_tool__pb2.GetDescriptorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tool.v1.ToolService/Execute',
            gibson_dot_tool_dot_v1_dot_tool__pb2.ExecuteRequest.SerializeToString,
            gibson_dot_tool_dot_v1_dot_tool__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tool.v1.ToolService/Health',
            gibson_dot_tool_dot_v1_dot_tool__pb2.HealthRequest.SerializeToString,
            gibson_dot_tool_dot_v1_dot_tool__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamExecute(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gibson.tool.v1.ToolService/StreamExecute',
            gibson_dot_tool_dot_v1_dot_tool__pb2.StreamExecuteRequest.SerializeToString,
            gibson_dot_tool_dot_v1_dot_tool__pb2.StreamExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
