# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gibson.daemon.v1 import daemon_pb2 as gibson_dot_daemon_dot_v1_dot_daemon__pb2
from gibson.manifest.v1 import manifest_pb2 as gibson_dot_manifest_dot_v1_dot_manifest__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gibson/daemon/v1/daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaemonServiceStub(object):
    """DaemonService provides the gRPC API for Gibson daemon client communication.

    This service exposes operational daemon functionality including mission execution,
    agent management, and real-time event streaming for the TUI and SDK clients.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/Connect',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ConnectRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/Ping',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.PingRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/Status',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StatusRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/gibson.daemon.v1.DaemonService/Subscribe',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.RunMission = channel.unary_stream(
                '/gibson.daemon.v1.DaemonService/RunMission',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.RunMissionRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.RunMissionResponse.FromString,
                _registered_method=True)
        self.StopMission = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/StopMission',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopMissionRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopMissionResponse.FromString,
                _registered_method=True)
        self.CreateMission = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/CreateMission',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionResponse.FromString,
                _registered_method=True)
        self.ListMissions = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/ListMissions',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionsResponse.FromString,
                _registered_method=True)
        self.PauseMission = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/PauseMission',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.PauseMissionRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.PauseMissionResponse.FromString,
                _registered_method=True)
        self.ResumeMission = channel.unary_stream(
                '/gibson.daemon.v1.DaemonService/ResumeMission',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ResumeMissionRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ResumeMissionResponse.FromString,
                _registered_method=True)
        self.GetMissionHistory = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/GetMissionHistory',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionHistoryRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionHistoryResponse.FromString,
                _registered_method=True)
        self.GetMissionCheckpoints = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/GetMissionCheckpoints',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionCheckpointsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionCheckpointsResponse.FromString,
                _registered_method=True)
        self.ListCheckpoints = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/ListCheckpoints',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListCheckpointsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListCheckpointsResponse.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/GetCheckpoint',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetCheckpointRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetCheckpointResponse.FromString,
                _registered_method=True)
        self.DiffCheckpoints = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/DiffCheckpoints',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.DiffCheckpointsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.DiffCheckpointsResponse.FromString,
                _registered_method=True)
        self.ListMissionDefinitions = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/ListMissionDefinitions',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionDefinitionsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionDefinitionsResponse.FromString,
                _registered_method=True)
        self.CreateMissionDefinition = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/CreateMissionDefinition',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionDefinitionRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionDefinitionResponse.FromString,
                _registered_method=True)
        self.UpdateMissionDefinition = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/UpdateMissionDefinition',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.UpdateMissionDefinitionRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.UpdateMissionDefinitionResponse.FromString,
                _registered_method=True)
        self.GetMissionDefinition = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/GetMissionDefinition',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionDefinitionRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionDefinitionResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/ListAgents',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.GetAgentStatus = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/GetAgentStatus',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetAgentStatusRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetAgentStatusResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/ListTools',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/ListPlugins',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListPluginsResponse.FromString,
                _registered_method=True)
        self.GetCapabilityManifest = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/GetCapabilityManifest',
                request_serializer=gibson_dot_manifest_dot_v1_dot_manifest__pb2.GetCapabilityManifestRequest.SerializeToString,
                response_deserializer=gibson_dot_manifest_dot_v1_dot_manifest__pb2.GetCapabilityManifestResponse.FromString,
                _registered_method=True)
        self.WatchManifestInvalidations = channel.unary_stream(
                '/gibson.daemon.v1.DaemonService/WatchManifestInvalidations',
                request_serializer=gibson_dot_manifest_dot_v1_dot_manifest__pb2.WatchManifestInvalidationsRequest.SerializeToString,
                response_deserializer=gibson_dot_manifest_dot_v1_dot_manifest__pb2.WatchManifestInvalidationsResponse.FromString,
                _registered_method=True)
        self.QueryPlugin = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/QueryPlugin',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.QueryPluginRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.QueryPluginResponse.FromString,
                _registered_method=True)
        self.StartComponent = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/StartComponent',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StartComponentRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StartComponentResponse.FromString,
                _registered_method=True)
        self.StopComponent = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/StopComponent',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopComponentRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopComponentResponse.FromString,
                _registered_method=True)
        self.BuildComponent = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/BuildComponent',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.BuildComponentRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.BuildComponentResponse.FromString,
                _registered_method=True)
        self.ShowComponent = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/ShowComponent',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ShowComponentRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ShowComponentResponse.FromString,
                _registered_method=True)
        self.GetComponentLogs = channel.unary_stream(
                '/gibson.daemon.v1.DaemonService/GetComponentLogs',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetComponentLogsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetComponentLogsResponse.FromString,
                _registered_method=True)
        self.GetMyPermissions = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/GetMyPermissions',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMyPermissionsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMyPermissionsResponse.FromString,
                _registered_method=True)
        self.ListMyMemberships = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/ListMyMemberships',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMyMembershipsRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMyMembershipsResponse.FromString,
                _registered_method=True)
        self.RenewCapabilityGrant = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/RenewCapabilityGrant',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.RenewCapabilityGrantRequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.RenewCapabilityGrantResponse.FromString,
                _registered_method=True)
        self.ValidateMissionCUE = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/ValidateMissionCUE',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ValidateMissionCUERequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ValidateMissionCUEResponse.FromString,
                _registered_method=True)
        self.CompleteMissionCUE = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/CompleteMissionCUE',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CompleteMissionCUERequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CompleteMissionCUEResponse.FromString,
                _registered_method=True)
        self.HoverMissionCUE = channel.unary_unary(
                '/gibson.daemon.v1.DaemonService/HoverMissionCUE',
                request_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.HoverMissionCUERequest.SerializeToString,
                response_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.HoverMissionCUEResponse.FromString,
                _registered_method=True)


class DaemonServiceServicer(object):
    """DaemonService provides the gRPC API for Gibson daemon client communication.

    This service exposes operational daemon functionality including mission execution,
    agent management, and real-time event streaming for the TUI and SDK clients.
    """

    def Connect(self, request, context):
        """Connect establishes a client connection to the daemon.
        Returns connection metadata and daemon version info.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping checks if the daemon is responsive.
        Used for health checks and connection validation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Status returns the current daemon status including uptime,
        service endpoints, and component counts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe establishes an event stream for TUI real-time updates.
        Streams mission events, agent events, finding events, etc.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunMission(self, request, context):
        """RunMission starts a mission and streams execution events.
        The stream remains open until the mission completes or is stopped.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMission(self, request, context):
        """StopMission gracefully stops a running mission.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMission(self, request, context):
        """CreateMission creates a new mission with target and mission-definition reference.
        Supports both referenced and inline configurations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMissions(self, request, context):
        """ListMissions returns all missions (past and active).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseMission(self, request, context):
        """PauseMission pauses a running mission at the next clean checkpoint boundary.
        If force is true, pauses immediately without waiting for a clean boundary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeMission(self, request, context):
        """ResumeMission resumes a paused mission from its last checkpoint.
        Returns a stream of mission events as execution continues.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMissionHistory(self, request, context):
        """GetMissionHistory returns all runs for a mission name, showing the
        complete history of mission executions with the same mission name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMissionCheckpoints(self, request, context):
        """GetMissionCheckpoints returns all checkpoints for a specific mission,
        providing visibility into saved execution states for resume capability.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCheckpoints(self, request, context):
        """ListCheckpoints returns a paginated, RBAC-scoped list of checkpoint
        summaries for a mission. Used by the dashboard checkpoint timeline.
        Spec: mission-checkpointing R13.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """GetCheckpoint returns the full decrypted payload of a single
        checkpoint for the dashboard's checkpoint detail panel. Secret
        redaction is enforced server-side by tenant role.
        Spec: mission-checkpointing R14.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiffCheckpoints(self, request, context):
        """DiffCheckpoints returns a server-computed diff between two checkpoints
        so the dashboard does not need to fetch and diff full payloads
        client-side. Spec: mission-checkpointing R15.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMissionDefinitions(self, request, context):
        """ListMissionDefinitions returns all installed mission definitions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMissionDefinition(self, request, context):
        """CreateMissionDefinition registers a structured mission definition with the
        daemon. This is the API-only replacement for the removed InstallMission RPC:
        the daemon does not clone git repositories or parse YAML; callers submit a
        fully-formed MissionDefinition proto (serialized from JSON in the CLI via
        protojson, or constructed natively in the dashboard).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMissionDefinition(self, request, context):
        """UpdateMissionDefinition replaces the content of an existing mission
        definition. The name field of the embedded definition is the lookup key.
        All other fields replace the stored definition; the server-assigned ID and
        original timestamps are preserved. Returns codes.NotFound if no definition
        with that name exists.
        Spec: gibson#437.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMissionDefinition(self, request, context):
        """GetMissionDefinition returns the full structured proto for a single
        installed mission definition, looked up by name. Use this instead of
        ListMissionDefinitions when the caller knows the definition name and
        needs every author-facing field (workspace, constraints, per-node
        retry/data/reuse policies). Returns codes.NotFound when the name is
        not registered.
        Spec: mission-author-experience M5 (gibson#134).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """ListAgents returns all registered agents from the etcd registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentStatus(self, request, context):
        """GetAgentStatus returns the current status of a specific agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """ListTools returns all registered tools from the etcd registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """ListPlugins returns all registered plugins from the etcd registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilityManifest(self, request, context):
        """GetCapabilityManifest returns the signed, versioned capability manifest
        for the calling principal in their resolved tenant. SDKs call this on
        session start and on invalidation events. The ADK calls it at scaffold
        time to discover what components, permissions, cross-component rules,
        and runtime limits apply.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchManifestInvalidations(self, request, context):
        """WatchManifestInvalidations streams ManifestInvalidationEvents to the
        caller whenever their resolved tenant's manifest is invalidated (FGA
        mutation, component registry change, tier update). Heartbeats are
        emitted periodically to keep the stream alive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPlugin(self, request, context):
        """QueryPlugin executes a method on a plugin and returns the result.
        The plugin must be registered in the etcd registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartComponent(self, request, context):
        """StartComponent starts a component (agent, tool, or plugin) by kind and name.
        The component must be installed in the local database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopComponent(self, request, context):
        """StopComponent stops a running component (agent, tool, or plugin) by kind and name.
        If force is true, sends SIGKILL immediately instead of graceful SIGTERM.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildComponent(self, request, context):
        """BuildComponent rebuilds a component (agent, tool, or plugin) from source.
        Useful for rebuilding after manual code changes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowComponent(self, request, context):
        """ShowComponent returns detailed information about a component.
        Includes manifest, status, paths, and lifecycle information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComponentLogs(self, request, context):
        """GetComponentLogs streams log entries for a component.
        Supports follow mode for continuous streaming and line limits.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyPermissions(self, request, context):
        """GetMyPermissions returns the current user's role, is_admin flag, component
        grants, and team memberships for the current tenant. Used by the
        dashboard's PermissionsCache to gate UI elements without per-click daemon
        calls.

        Auth: self-mode (spec: self-mode-authz). The hotfix `unauthenticated: true`
        is replaced with `self: true + allowed_identities: USER`. This RPC may be
        called before the active-tenant cookie is set (which made the earlier
        `tenant_from_identity` FGA check fail with "no tenant derivable"), so no
        FGA tuple lookup is performed. The four defense layers are preserved:
        (a) Envoy `jwt_authn` validates the Zitadel JWT before ext-authz.
        (b) ext-authz mints X-Gibson-Identity-Subject from the verified sub —
        clients cannot forge it.
        (c) The daemon's SPIFFE mTLS init is fail-closed (zero-trust-hardening
        Req 1) so non-Envoy callers cannot reach the listener.
        (d) ext-authz enforces allowed_identities: only USER tokens are accepted.
        The handler scopes the response strictly to the caller's verified subject.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyMemberships(self, request, context):
        """ListMyMemberships returns every tenant the authenticated caller is a
        member of, with the caller's role per tenant. Identity comes from the
        call context; no tenant_id parameter — this RPC discovers the caller's
        tenants. Used by the dashboard at sign-in time to populate the tenant
        picker / set the active-tenant cookie.

        Auth: self-mode (spec: self-mode-authz). The hotfix `unauthenticated: true`
        is replaced with `self: true + allowed_identities: USER`. By definition this
        RPC runs before the caller's active tenant is known, so a
        `tenant_from_identity` deriver would always fail "no tenant derivable". The
        same four defense layers as GetMyPermissions apply; see that method for the
        full contract. The handler self-scopes the membership list to the verified
        caller subject.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewCapabilityGrant(self, request, context):
        """RenewCapabilityGrant mints a fresh capability-grant JWT for an
        ongoing mission task whose existing CG-JWT is approaching its
        ≤30-minute expiry. Long-running missions (vuln research, broad
        recon sweeps, multi-host fuzzing) call this before their current
        CG-JWT expires so callbacks keep flowing without dispatching a
        fresh task.

        Authorization: the caller MUST present a valid (non-expired)
        CG-JWT whose subject matches the request's agent_id and whose
        mission_id/task_id match the request. Renewal is rate-limited
        per agent to prevent abuse.

        Spec: unified-identity-and-authorization Requirement 5.8.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateMissionCUE(self, request, context):
        """ValidateMissionCUE compiles a CUE mission snippet and returns diagnostics.
        Powers the dashboard CUE editor's real-time error squiggles, and is now
        callable by ADK/SDK users with a single user token. An empty diagnostics
        list means the source is valid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteMissionCUE(self, request, context):
        """CompleteMissionCUE returns completion candidates at a cursor position.
        Powers the dashboard CUE editor's auto-complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HoverMissionCUE(self, request, context):
        """HoverMissionCUE returns type and documentation for a position in CUE source.
        Powers the dashboard CUE editor's hover tooltip.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ConnectRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ConnectResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.PingRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.PingResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StatusRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StatusResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.SubscribeRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.SubscribeResponse.SerializeToString,
            ),
            'RunMission': grpc.unary_stream_rpc_method_handler(
                    servicer.RunMission,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.RunMissionRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.RunMissionResponse.SerializeToString,
            ),
            'StopMission': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMission,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopMissionRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopMissionResponse.SerializeToString,
            ),
            'CreateMission': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMission,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionResponse.SerializeToString,
            ),
            'ListMissions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMissions,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionsResponse.SerializeToString,
            ),
            'PauseMission': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseMission,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.PauseMissionRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.PauseMissionResponse.SerializeToString,
            ),
            'ResumeMission': grpc.unary_stream_rpc_method_handler(
                    servicer.ResumeMission,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ResumeMissionRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ResumeMissionResponse.SerializeToString,
            ),
            'GetMissionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMissionHistory,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionHistoryRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionHistoryResponse.SerializeToString,
            ),
            'GetMissionCheckpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMissionCheckpoints,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionCheckpointsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionCheckpointsResponse.SerializeToString,
            ),
            'ListCheckpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCheckpoints,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListCheckpointsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListCheckpointsResponse.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetCheckpointRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetCheckpointResponse.SerializeToString,
            ),
            'DiffCheckpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.DiffCheckpoints,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.DiffCheckpointsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.DiffCheckpointsResponse.SerializeToString,
            ),
            'ListMissionDefinitions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMissionDefinitions,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionDefinitionsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionDefinitionsResponse.SerializeToString,
            ),
            'CreateMissionDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMissionDefinition,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionDefinitionRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionDefinitionResponse.SerializeToString,
            ),
            'UpdateMissionDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMissionDefinition,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.UpdateMissionDefinitionRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.UpdateMissionDefinitionResponse.SerializeToString,
            ),
            'GetMissionDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMissionDefinition,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionDefinitionRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionDefinitionResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListAgentsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListAgentsResponse.SerializeToString,
            ),
            'GetAgentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentStatus,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetAgentStatusRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetAgentStatusResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListToolsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListToolsResponse.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListPluginsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListPluginsResponse.SerializeToString,
            ),
            'GetCapabilityManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilityManifest,
                    request_deserializer=gibson_dot_manifest_dot_v1_dot_manifest__pb2.GetCapabilityManifestRequest.FromString,
                    response_serializer=gibson_dot_manifest_dot_v1_dot_manifest__pb2.GetCapabilityManifestResponse.SerializeToString,
            ),
            'WatchManifestInvalidations': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchManifestInvalidations,
                    request_deserializer=gibson_dot_manifest_dot_v1_dot_manifest__pb2.WatchManifestInvalidationsRequest.FromString,
                    response_serializer=gibson_dot_manifest_dot_v1_dot_manifest__pb2.WatchManifestInvalidationsResponse.SerializeToString,
            ),
            'QueryPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPlugin,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.QueryPluginRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.QueryPluginResponse.SerializeToString,
            ),
            'StartComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.StartComponent,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StartComponentRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StartComponentResponse.SerializeToString,
            ),
            'StopComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.StopComponent,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopComponentRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopComponentResponse.SerializeToString,
            ),
            'BuildComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildComponent,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.BuildComponentRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.BuildComponentResponse.SerializeToString,
            ),
            'ShowComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowComponent,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ShowComponentRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ShowComponentResponse.SerializeToString,
            ),
            'GetComponentLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetComponentLogs,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetComponentLogsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetComponentLogsResponse.SerializeToString,
            ),
            'GetMyPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyPermissions,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMyPermissionsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMyPermissionsResponse.SerializeToString,
            ),
            'ListMyMemberships': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyMemberships,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMyMembershipsRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMyMembershipsResponse.SerializeToString,
            ),
            'RenewCapabilityGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewCapabilityGrant,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.RenewCapabilityGrantRequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.RenewCapabilityGrantResponse.SerializeToString,
            ),
            'ValidateMissionCUE': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateMissionCUE,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ValidateMissionCUERequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.ValidateMissionCUEResponse.SerializeToString,
            ),
            'CompleteMissionCUE': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteMissionCUE,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CompleteMissionCUERequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.CompleteMissionCUEResponse.SerializeToString,
            ),
            'HoverMissionCUE': grpc.unary_unary_rpc_method_handler(
                    servicer.HoverMissionCUE,
                    request_deserializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.HoverMissionCUERequest.FromString,
                    response_serializer=gibson_dot_daemon_dot_v1_dot_daemon__pb2.HoverMissionCUEResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gibson.daemon.v1.DaemonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gibson.daemon.v1.DaemonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaemonService(object):
    """DaemonService provides the gRPC API for Gibson daemon client communication.

    This service exposes operational daemon functionality including mission execution,
    agent management, and real-time event streaming for the TUI and SDK clients.
    """

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/Connect',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ConnectRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/Ping',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.PingRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/Status',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.StatusRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/Subscribe',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.SubscribeRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/RunMission',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.RunMissionRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.RunMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/StopMission',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopMissionRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/CreateMission',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/ListMissions',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/PauseMission',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.PauseMissionRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.PauseMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/ResumeMission',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ResumeMissionRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ResumeMissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMissionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/GetMissionHistory',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionHistoryRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMissionCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/GetMissionCheckpoints',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionCheckpointsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionCheckpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/ListCheckpoints',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListCheckpointsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListCheckpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/GetCheckpoint',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetCheckpointRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiffCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/DiffCheckpoints',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.DiffCheckpointsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.DiffCheckpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMissionDefinitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/ListMissionDefinitions',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionDefinitionsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMissionDefinitionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMissionDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/CreateMissionDefinition',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionDefinitionRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.CreateMissionDefinitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMissionDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/UpdateMissionDefinition',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.UpdateMissionDefinitionRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.UpdateMissionDefinitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMissionDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/GetMissionDefinition',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionDefinitionRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMissionDefinitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/ListAgents',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListAgentsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/GetAgentStatus',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetAgentStatusRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetAgentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/ListTools',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListToolsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/ListPlugins',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListPluginsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilityManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/GetCapabilityManifest',
            gibson_dot_manifest_dot_v1_dot_manifest__pb2.GetCapabilityManifestRequest.SerializeToString,
            gibson_dot_manifest_dot_v1_dot_manifest__pb2.GetCapabilityManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchManifestInvalidations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/WatchManifestInvalidations',
            gibson_dot_manifest_dot_v1_dot_manifest__pb2.WatchManifestInvalidationsRequest.SerializeToString,
            gibson_dot_manifest_dot_v1_dot_manifest__pb2.WatchManifestInvalidationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/QueryPlugin',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.QueryPluginRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.QueryPluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/StartComponent',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.StartComponentRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.StartComponentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/StopComponent',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopComponentRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.StopComponentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/BuildComponent',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.BuildComponentRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.BuildComponentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/ShowComponent',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ShowComponentRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ShowComponentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComponentLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/GetComponentLogs',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetComponentLogsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetComponentLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/GetMyPermissions',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMyPermissionsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.GetMyPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyMemberships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/ListMyMemberships',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMyMembershipsRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ListMyMembershipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewCapabilityGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/RenewCapabilityGrant',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.RenewCapabilityGrantRequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.RenewCapabilityGrantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateMissionCUE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/ValidateMissionCUE',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ValidateMissionCUERequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.ValidateMissionCUEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteMissionCUE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/CompleteMissionCUE',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.CompleteMissionCUERequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.CompleteMissionCUEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HoverMissionCUE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.daemon.v1.DaemonService/HoverMissionCUE',
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.HoverMissionCUERequest.SerializeToString,
            gibson_dot_daemon_dot_v1_dot_daemon__pb2.HoverMissionCUEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
