# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gibson.identity.v1 import identity_pb2 as gibson_dot_identity_dot_v1_dot_identity__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gibson/identity/v1/identity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityServiceStub(object):
    """IdentityService exposes the "describe me" RPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WhoAmI = channel.unary_unary(
                '/gibson.identity.v1.IdentityService/WhoAmI',
                request_serializer=gibson_dot_identity_dot_v1_dot_identity__pb2.WhoAmIRequest.SerializeToString,
                response_deserializer=gibson_dot_identity_dot_v1_dot_identity__pb2.WhoAmIResponse.FromString,
                _registered_method=True)


class IdentityServiceServicer(object):
    """IdentityService exposes the "describe me" RPC.
    """

    def WhoAmI(self, request, context):
        """WhoAmI returns the caller's effective FGA grants. When
        target_principal_id is set, the caller MUST be tenant_admin on
        the target's tenant — otherwise the daemon returns
        PermissionDenied. Identity is derived from ext-authz-emitted
        headers, never from the request body.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WhoAmI': grpc.unary_unary_rpc_method_handler(
                    servicer.WhoAmI,
                    request_deserializer=gibson_dot_identity_dot_v1_dot_identity__pb2.WhoAmIRequest.FromString,
                    response_serializer=gibson_dot_identity_dot_v1_dot_identity__pb2.WhoAmIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gibson.identity.v1.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gibson.identity.v1.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService(object):
    """IdentityService exposes the "describe me" RPC.
    """

    @staticmethod
    def WhoAmI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.identity.v1.IdentityService/WhoAmI',
            gibson_dot_identity_dot_v1_dot_identity__pb2.WhoAmIRequest.SerializeToString,
            gibson_dot_identity_dot_v1_dot_identity__pb2.WhoAmIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
