# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from intelligence.v1 import intelligence_pb2 as intelligence_dot_v1_dot_intelligence__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in intelligence/v1/intelligence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntelligenceServiceStub(object):
    """IntelligenceService provides cross-mission security intelligence queries.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecurringVulnerabilities = channel.unary_unary(
                '/intelligence.v1.IntelligenceService/GetRecurringVulnerabilities',
                request_serializer=intelligence_dot_v1_dot_intelligence__pb2.GetRecurringVulnerabilitiesRequest.SerializeToString,
                response_deserializer=intelligence_dot_v1_dot_intelligence__pb2.GetRecurringVulnerabilitiesResponse.FromString,
                _registered_method=True)
        self.GetRemediationMetrics = channel.unary_unary(
                '/intelligence.v1.IntelligenceService/GetRemediationMetrics',
                request_serializer=intelligence_dot_v1_dot_intelligence__pb2.GetRemediationMetricsRequest.SerializeToString,
                response_deserializer=intelligence_dot_v1_dot_intelligence__pb2.GetRemediationMetricsResponse.FromString,
                _registered_method=True)
        self.GetAssetRiskScore = channel.unary_unary(
                '/intelligence.v1.IntelligenceService/GetAssetRiskScore',
                request_serializer=intelligence_dot_v1_dot_intelligence__pb2.GetAssetRiskScoreRequest.SerializeToString,
                response_deserializer=intelligence_dot_v1_dot_intelligence__pb2.GetAssetRiskScoreResponse.FromString,
                _registered_method=True)
        self.GetAttackPatterns = channel.unary_unary(
                '/intelligence.v1.IntelligenceService/GetAttackPatterns',
                request_serializer=intelligence_dot_v1_dot_intelligence__pb2.GetAttackPatternsRequest.SerializeToString,
                response_deserializer=intelligence_dot_v1_dot_intelligence__pb2.GetAttackPatternsResponse.FromString,
                _registered_method=True)
        self.GetSimilarTargets = channel.unary_unary(
                '/intelligence.v1.IntelligenceService/GetSimilarTargets',
                request_serializer=intelligence_dot_v1_dot_intelligence__pb2.GetSimilarTargetsRequest.SerializeToString,
                response_deserializer=intelligence_dot_v1_dot_intelligence__pb2.GetSimilarTargetsResponse.FromString,
                _registered_method=True)


class IntelligenceServiceServicer(object):
    """IntelligenceService provides cross-mission security intelligence queries.
    """

    def GetRecurringVulnerabilities(self, request, context):
        """GetRecurringVulnerabilities finds vulnerabilities appearing across multiple targets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRemediationMetrics(self, request, context):
        """GetRemediationMetrics calculates remediation success rates and timing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssetRiskScore(self, request, context):
        """GetAssetRiskScore calculates risk scores for assets based on historical findings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttackPatterns(self, request, context):
        """GetAttackPatterns identifies successful attack technique sequences.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimilarTargets(self, request, context):
        """GetSimilarTargets finds targets similar to a reference target.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelligenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecurringVulnerabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecurringVulnerabilities,
                    request_deserializer=intelligence_dot_v1_dot_intelligence__pb2.GetRecurringVulnerabilitiesRequest.FromString,
                    response_serializer=intelligence_dot_v1_dot_intelligence__pb2.GetRecurringVulnerabilitiesResponse.SerializeToString,
            ),
            'GetRemediationMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRemediationMetrics,
                    request_deserializer=intelligence_dot_v1_dot_intelligence__pb2.GetRemediationMetricsRequest.FromString,
                    response_serializer=intelligence_dot_v1_dot_intelligence__pb2.GetRemediationMetricsResponse.SerializeToString,
            ),
            'GetAssetRiskScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssetRiskScore,
                    request_deserializer=intelligence_dot_v1_dot_intelligence__pb2.GetAssetRiskScoreRequest.FromString,
                    response_serializer=intelligence_dot_v1_dot_intelligence__pb2.GetAssetRiskScoreResponse.SerializeToString,
            ),
            'GetAttackPatterns': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttackPatterns,
                    request_deserializer=intelligence_dot_v1_dot_intelligence__pb2.GetAttackPatternsRequest.FromString,
                    response_serializer=intelligence_dot_v1_dot_intelligence__pb2.GetAttackPatternsResponse.SerializeToString,
            ),
            'GetSimilarTargets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimilarTargets,
                    request_deserializer=intelligence_dot_v1_dot_intelligence__pb2.GetSimilarTargetsRequest.FromString,
                    response_serializer=intelligence_dot_v1_dot_intelligence__pb2.GetSimilarTargetsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'intelligence.v1.IntelligenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('intelligence.v1.IntelligenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntelligenceService(object):
    """IntelligenceService provides cross-mission security intelligence queries.
    """

    @staticmethod
    def GetRecurringVulnerabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intelligence.v1.IntelligenceService/GetRecurringVulnerabilities',
            intelligence_dot_v1_dot_intelligence__pb2.GetRecurringVulnerabilitiesRequest.SerializeToString,
            intelligence_dot_v1_dot_intelligence__pb2.GetRecurringVulnerabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRemediationMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intelligence.v1.IntelligenceService/GetRemediationMetrics',
            intelligence_dot_v1_dot_intelligence__pb2.GetRemediationMetricsRequest.SerializeToString,
            intelligence_dot_v1_dot_intelligence__pb2.GetRemediationMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssetRiskScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intelligence.v1.IntelligenceService/GetAssetRiskScore',
            intelligence_dot_v1_dot_intelligence__pb2.GetAssetRiskScoreRequest.SerializeToString,
            intelligence_dot_v1_dot_intelligence__pb2.GetAssetRiskScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttackPatterns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intelligence.v1.IntelligenceService/GetAttackPatterns',
            intelligence_dot_v1_dot_intelligence__pb2.GetAttackPatternsRequest.SerializeToString,
            intelligence_dot_v1_dot_intelligence__pb2.GetAttackPatternsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSimilarTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intelligence.v1.IntelligenceService/GetSimilarTargets',
            intelligence_dot_v1_dot_intelligence__pb2.GetSimilarTargetsRequest.SerializeToString,
            intelligence_dot_v1_dot_intelligence__pb2.GetSimilarTargetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
