# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gibson.graph.v1 import graph_pb2 as gibson_dot_graph_dot_v1_dot_graph__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gibson/graph/v1/graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphServiceStub(object):
    """GraphService serves per-tenant knowledge-graph reads and a server-streaming
    update feed. Every RPC routes through Pool.For(tenant).Neo4j() server-side
    and is gated by the FGA tenant.member relation at ext-authz.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTenantGraph = channel.unary_unary(
                '/gibson.graph.v1.GraphService/GetTenantGraph',
                request_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetTenantGraphRequest.SerializeToString,
                response_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetTenantGraphResponse.FromString,
                _registered_method=True)
        self.GetMissionGraph = channel.unary_unary(
                '/gibson.graph.v1.GraphService/GetMissionGraph',
                request_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetMissionGraphRequest.SerializeToString,
                response_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetMissionGraphResponse.FromString,
                _registered_method=True)
        self.QueryPaths = channel.unary_unary(
                '/gibson.graph.v1.GraphService/QueryPaths',
                request_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.QueryPathsRequest.SerializeToString,
                response_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.QueryPathsResponse.FromString,
                _registered_method=True)
        self.WatchGraphUpdates = channel.unary_stream(
                '/gibson.graph.v1.GraphService/WatchGraphUpdates',
                request_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.WatchGraphUpdatesRequest.SerializeToString,
                response_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GraphUpdate.FromString,
                _registered_method=True)
        self.GetFindingCounts = channel.unary_unary(
                '/gibson.graph.v1.GraphService/GetFindingCounts',
                request_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingCountsRequest.SerializeToString,
                response_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingCountsResponse.FromString,
                _registered_method=True)
        self.GetFindingTimeSeries = channel.unary_unary(
                '/gibson.graph.v1.GraphService/GetFindingTimeSeries',
                request_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingTimeSeriesRequest.SerializeToString,
                response_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingTimeSeriesResponse.FromString,
                _registered_method=True)
        self.GetGraphStats = channel.unary_unary(
                '/gibson.graph.v1.GraphService/GetGraphStats',
                request_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphStatsRequest.SerializeToString,
                response_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphStatsResponse.FromString,
                _registered_method=True)
        self.GetGraphSummary = channel.unary_unary(
                '/gibson.graph.v1.GraphService/GetGraphSummary',
                request_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphSummaryRequest.SerializeToString,
                response_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphSummaryResponse.FromString,
                _registered_method=True)
        self.GetGraphContext = channel.unary_unary(
                '/gibson.graph.v1.GraphService/GetGraphContext',
                request_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphContextRequest.SerializeToString,
                response_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphContextResponse.FromString,
                _registered_method=True)
        self.GetFindings = channel.unary_unary(
                '/gibson.graph.v1.GraphService/GetFindings',
                request_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingsRequest.SerializeToString,
                response_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingsResponse.FromString,
                _registered_method=True)


class GraphServiceServicer(object):
    """GraphService serves per-tenant knowledge-graph reads and a server-streaming
    update feed. Every RPC routes through Pool.For(tenant).Neo4j() server-side
    and is gated by the FGA tenant.member relation at ext-authz.
    """

    def GetTenantGraph(self, request, context):
        """GetTenantGraph returns the full per-tenant subgraph subject to a server-side
        node-count cap. Use limit + include_labels to narrow scope.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMissionGraph(self, request, context):
        """GetMissionGraph returns the subgraph touched by a single mission run.
        Mission ownership is enforced by FGA + by `WHERE m.tenant_id = $tenant`
        in the underlying Cypher (defense in depth).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPaths(self, request, context):
        """QueryPaths runs a bounded path query from `from_node_id` to either a
        specific `to_node_id` or any node of `to_node_kind`, up to `max_depth`.
        Server caps: depth ≤ 10, paths ≤ 100, query timeout 5s.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchGraphUpdates(self, request, context):
        """WatchGraphUpdates server-streams new node/edge writes for the calling
        tenant. Subscribers should treat the stream as a UX hint, not a source of
        truth — drops are possible under load. Reconnect with exponential
        backoff; fall back to polling GetTenantGraph if the stream stays
        unhealthy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFindingCounts(self, request, context):
        """GetFindingCounts returns finding counts grouped by severity or category.
        Replaces the dashboard's prior direct-Neo4j paths in
        gibson-client.ts (getKPIs, getFindingsBySeverity, getFindingsByCategory)
        and app/api/findings/counts/route.ts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFindingTimeSeries(self, request, context):
        """GetFindingTimeSeries returns finding counts bucketed by day for the last
        N days (default 30, max 365). Missing days are returned as zero buckets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraphStats(self, request, context):
        """GetGraphStats returns aggregate stats for the per-tenant knowledge graph:
        node counts by label, total edges, last-write timestamp.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraphSummary(self, request, context):
        """GetGraphSummary returns an LLM-friendly text summary of the per-tenant
        graph plus structured stats. Server-side caches results for 60s per
        tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraphContext(self, request, context):
        """GetGraphContext returns a focus node and its bounded neighborhood, used
        by the chatbot to enrich its system prompt. Returns an empty response
        (focus_node unset) on missing node or NotProvisioned — does NOT error,
        so the chatbot prompt never breaks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFindings(self, request, context):
        """GetFindings returns a paginated, filterable list of findings (and
        vulnerabilities) for the calling tenant. Replaces the dashboard's
        direct-Neo4j paths in app/api/findings/route.ts,
        app/api/missions/[id]/findings/route.ts, and the iteration backing
        findings export.
        Spec: dashboard-neo4j-crud-removal Req 1.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTenantGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantGraph,
                    request_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetTenantGraphRequest.FromString,
                    response_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetTenantGraphResponse.SerializeToString,
            ),
            'GetMissionGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMissionGraph,
                    request_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetMissionGraphRequest.FromString,
                    response_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetMissionGraphResponse.SerializeToString,
            ),
            'QueryPaths': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPaths,
                    request_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.QueryPathsRequest.FromString,
                    response_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.QueryPathsResponse.SerializeToString,
            ),
            'WatchGraphUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchGraphUpdates,
                    request_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.WatchGraphUpdatesRequest.FromString,
                    response_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GraphUpdate.SerializeToString,
            ),
            'GetFindingCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFindingCounts,
                    request_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingCountsRequest.FromString,
                    response_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingCountsResponse.SerializeToString,
            ),
            'GetFindingTimeSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFindingTimeSeries,
                    request_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingTimeSeriesRequest.FromString,
                    response_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingTimeSeriesResponse.SerializeToString,
            ),
            'GetGraphStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphStats,
                    request_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphStatsRequest.FromString,
                    response_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphStatsResponse.SerializeToString,
            ),
            'GetGraphSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphSummary,
                    request_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphSummaryRequest.FromString,
                    response_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphSummaryResponse.SerializeToString,
            ),
            'GetGraphContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphContext,
                    request_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphContextRequest.FromString,
                    response_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphContextResponse.SerializeToString,
            ),
            'GetFindings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFindings,
                    request_deserializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingsRequest.FromString,
                    response_serializer=gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gibson.graph.v1.GraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gibson.graph.v1.GraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphService(object):
    """GraphService serves per-tenant knowledge-graph reads and a server-streaming
    update feed. Every RPC routes through Pool.For(tenant).Neo4j() server-side
    and is gated by the FGA tenant.member relation at ext-authz.
    """

    @staticmethod
    def GetTenantGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.graph.v1.GraphService/GetTenantGraph',
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetTenantGraphRequest.SerializeToString,
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetTenantGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMissionGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.graph.v1.GraphService/GetMissionGraph',
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetMissionGraphRequest.SerializeToString,
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetMissionGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPaths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.graph.v1.GraphService/QueryPaths',
            gibson_dot_graph_dot_v1_dot_graph__pb2.QueryPathsRequest.SerializeToString,
            gibson_dot_graph_dot_v1_dot_graph__pb2.QueryPathsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchGraphUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gibson.graph.v1.GraphService/WatchGraphUpdates',
            gibson_dot_graph_dot_v1_dot_graph__pb2.WatchGraphUpdatesRequest.SerializeToString,
            gibson_dot_graph_dot_v1_dot_graph__pb2.GraphUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFindingCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.graph.v1.GraphService/GetFindingCounts',
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingCountsRequest.SerializeToString,
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingCountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFindingTimeSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.graph.v1.GraphService/GetFindingTimeSeries',
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingTimeSeriesRequest.SerializeToString,
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingTimeSeriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraphStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.graph.v1.GraphService/GetGraphStats',
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphStatsRequest.SerializeToString,
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraphSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.graph.v1.GraphService/GetGraphSummary',
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphSummaryRequest.SerializeToString,
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraphContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.graph.v1.GraphService/GetGraphContext',
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphContextRequest.SerializeToString,
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetGraphContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.graph.v1.GraphService/GetFindings',
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingsRequest.SerializeToString,
            gibson_dot_graph_dot_v1_dot_graph__pb2.GetFindingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
