# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gibson.plugin.v1 import invoke_pb2 as gibson_dot_plugin_dot_v1_dot_invoke__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gibson/plugin/v1/invoke_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginInvokeServiceStub(object):
    """PluginInvokeService is the tool-callable RPC for invoking plugin methods.
    Tools call PluginInvoke; the daemon validates authz, looks up an active plugin
    install, enqueues a work item via the existing ComponentService PollWork model,
    awaits SubmitResult, and forwards the result to the tool. Plugin business
    methods themselves are NOT defined here — the plugin's manifest declares its
    own method set per the plugin-runtime manifest spec, and the dispatch is by
    method-name string carried in PluginInvokeRequest.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PluginInvoke = channel.unary_unary(
                '/gibson.plugin.v1.PluginInvokeService/PluginInvoke',
                request_serializer=gibson_dot_plugin_dot_v1_dot_invoke__pb2.PluginInvokeRequest.SerializeToString,
                response_deserializer=gibson_dot_plugin_dot_v1_dot_invoke__pb2.PluginInvokeResponse.FromString,
                _registered_method=True)


class PluginInvokeServiceServicer(object):
    """PluginInvokeService is the tool-callable RPC for invoking plugin methods.
    Tools call PluginInvoke; the daemon validates authz, looks up an active plugin
    install, enqueues a work item via the existing ComponentService PollWork model,
    awaits SubmitResult, and forwards the result to the tool. Plugin business
    methods themselves are NOT defined here — the plugin's manifest declares its
    own method set per the plugin-runtime manifest spec, and the dispatch is by
    method-name string carried in PluginInvokeRequest.
    """

    def PluginInvoke(self, request, context):
        """PluginInvoke routes a typed invocation to a serving plugin install.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginInvokeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PluginInvoke': grpc.unary_unary_rpc_method_handler(
                    servicer.PluginInvoke,
                    request_deserializer=gibson_dot_plugin_dot_v1_dot_invoke__pb2.PluginInvokeRequest.FromString,
                    response_serializer=gibson_dot_plugin_dot_v1_dot_invoke__pb2.PluginInvokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gibson.plugin.v1.PluginInvokeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gibson.plugin.v1.PluginInvokeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginInvokeService(object):
    """PluginInvokeService is the tool-callable RPC for invoking plugin methods.
    Tools call PluginInvoke; the daemon validates authz, looks up an active plugin
    install, enqueues a work item via the existing ComponentService PollWork model,
    awaits SubmitResult, and forwards the result to the tool. Plugin business
    methods themselves are NOT defined here — the plugin's manifest declares its
    own method set per the plugin-runtime manifest spec, and the dispatch is by
    method-name string carried in PluginInvokeRequest.
    """

    @staticmethod
    def PluginInvoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.plugin.v1.PluginInvokeService/PluginInvoke',
            gibson_dot_plugin_dot_v1_dot_invoke__pb2.PluginInvokeRequest.SerializeToString,
            gibson_dot_plugin_dot_v1_dot_invoke__pb2.PluginInvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
