# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gibson/plugin/v1/invoke.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gibson/plugin/v1/invoke.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from gibson.auth.v1 import options_pb2 as gibson_dot_auth_dot_v1_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgibson/plugin/v1/invoke.proto\x12\x10gibson.plugin.v1\x1a\x19google/protobuf/any.proto\x1a\x1cgibson/auth/v1/options.proto\"v\n\x13PluginInvokeRequest\x12\x13\n\x0bplugin_name\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12%\n\x07request\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x13\n\x0b\x64\x65\x61\x64line_ms\x18\x04 \x01(\x03\"j\n\x14PluginInvokeResponse\x12$\n\x06result\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12,\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1d.gibson.plugin.v1.PluginError\"\xda\x02\n\x0bPluginError\x12\x30\n\x04kind\x18\x01 \x01(\x0e\x32\".gibson.plugin.v1.PluginError.Kind\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x87\x02\n\x04Kind\x12!\n\x1dPLUGIN_ERROR_KIND_UNSPECIFIED\x10\x00\x12!\n\x1dPLUGIN_ERROR_KIND_UNAVAILABLE\x10\x01\x12\"\n\x1ePLUGIN_ERROR_KIND_UNAUTHORIZED\x10\x02\x12&\n\"PLUGIN_ERROR_KIND_METHOD_NOT_FOUND\x10\x03\x12\'\n#PLUGIN_ERROR_KIND_DEADLINE_EXCEEDED\x10\x04\x12$\n PLUGIN_ERROR_KIND_HANDLER_FAILED\x10\x05\x12\x1e\n\x1aPLUGIN_ERROR_KIND_INTERNAL\x10\x06\x32\xb1\x01\n\x13PluginInvokeService\x12\x99\x01\n\x0cPluginInvoke\x12%.gibson.plugin.v1.PluginInvokeRequest\x1a&.gibson.plugin.v1.PluginInvokeResponse\":\x8a\xb5\x18\x36\n\ncan_invoke\x12\x06plugin\x1a\x1etenant_and_field(\'PluginName\') \x04\x42PP\x01Z<github.com/zero-day-ai/sdk/api/gen/gibson/plugin/v1;pluginpb\xaa\x02\rGibson.Pluginb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gibson.plugin.v1.invoke_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001Z<github.com/zero-day-ai/sdk/api/gen/gibson/plugin/v1;pluginpb\252\002\rGibson.Plugin'
  _globals['_PLUGININVOKESERVICE'].methods_by_name['PluginInvoke']._loaded_options = None
  _globals['_PLUGININVOKESERVICE'].methods_by_name['PluginInvoke']._serialized_options = b'\212\265\0306\n\ncan_invoke\022\006plugin\032\036tenant_and_field(\'PluginName\') \004'
  _globals['_PLUGININVOKEREQUEST']._serialized_start=108
  _globals['_PLUGININVOKEREQUEST']._serialized_end=226
  _globals['_PLUGININVOKERESPONSE']._serialized_start=228
  _globals['_PLUGININVOKERESPONSE']._serialized_end=334
  _globals['_PLUGINERROR']._serialized_start=337
  _globals['_PLUGINERROR']._serialized_end=683
  _globals['_PLUGINERROR_KIND']._serialized_start=420
  _globals['_PLUGINERROR_KIND']._serialized_end=683
  _globals['_PLUGININVOKESERVICE']._serialized_start=686
  _globals['_PLUGININVOKESERVICE']._serialized_end=863
# @@protoc_insertion_point(module_scope)
