# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gibson.tenant.v1 import tenant_pb2 as gibson_dot_tenant_dot_v1_dot_tenant__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gibson/tenant/v1/tenant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TenantServiceStub(object):
    """TenantService provides customer-callable tenant-management operations.
    ---------------------------------------------------------------------------
    Agent identities
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAgentIdentity = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/CreateAgentIdentity',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateAgentIdentityRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateAgentIdentityResponse.FromString,
                _registered_method=True)
        self.ListAgentIdentities = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/ListAgentIdentities',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAgentIdentitiesRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAgentIdentitiesResponse.FromString,
                _registered_method=True)
        self.RevokeAgentIdentity = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/RevokeAgentIdentity',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.RevokeAgentIdentityRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.RevokeAgentIdentityResponse.FromString,
                _registered_method=True)
        self.GetOnboardingState = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/GetOnboardingState',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetOnboardingStateRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetOnboardingStateResponse.FromString,
                _registered_method=True)
        self.UpdateOnboardingState = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/UpdateOnboardingState',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateOnboardingStateRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateOnboardingStateResponse.FromString,
                _registered_method=True)
        self.GetTenantQuota = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/GetTenantQuota',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaResponse.FromString,
                _registered_method=True)
        self.GetTenantQuotaUsage = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/GetTenantQuotaUsage',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaUsageRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaUsageResponse.FromString,
                _registered_method=True)
        self.ListAuditEvents = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/ListAuditEvents',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAuditEventsRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAuditEventsResponse.FromString,
                _registered_method=True)
        self.ExportFindings = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/ExportFindings',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExportFindingsRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExportFindingsResponse.FromString,
                _registered_method=True)
        self.SaveMissionDraft = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/SaveMissionDraft',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SaveMissionDraftRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SaveMissionDraftResponse.FromString,
                _registered_method=True)
        self.ListMissionDrafts = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/ListMissionDrafts',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListMissionDraftsRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListMissionDraftsResponse.FromString,
                _registered_method=True)
        self.GetMissionDraft = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/GetMissionDraft',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetMissionDraftRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetMissionDraftResponse.FromString,
                _registered_method=True)
        self.DeleteMissionDraft = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/DeleteMissionDraft',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteMissionDraftRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteMissionDraftResponse.FromString,
                _registered_method=True)
        self.ListProviders = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/ListProviders',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProvidersRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProvidersResponse.FromString,
                _registered_method=True)
        self.GetProvider = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/GetProvider',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderResponse.FromString,
                _registered_method=True)
        self.CreateProvider = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/CreateProvider',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateProviderRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateProviderResponse.FromString,
                _registered_method=True)
        self.UpdateProvider = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/UpdateProvider',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateProviderRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateProviderResponse.FromString,
                _registered_method=True)
        self.DeleteProvider = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/DeleteProvider',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteProviderRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteProviderResponse.FromString,
                _registered_method=True)
        self.TestProvider = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/TestProvider',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.TestProviderRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.TestProviderResponse.FromString,
                _registered_method=True)
        self.GetSupportedProviders = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/GetSupportedProviders',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetSupportedProvidersRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetSupportedProvidersResponse.FromString,
                _registered_method=True)
        self.ListProviderModels = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/ListProviderModels',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProviderModelsRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProviderModelsResponse.FromString,
                _registered_method=True)
        self.GetProviderHealth = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/GetProviderHealth',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderHealthRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderHealthResponse.FromString,
                _registered_method=True)
        self.GetDefaultProvider = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/GetDefaultProvider',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetDefaultProviderRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetDefaultProviderResponse.FromString,
                _registered_method=True)
        self.SetDefaultProvider = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/SetDefaultProvider',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetDefaultProviderRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetDefaultProviderResponse.FromString,
                _registered_method=True)
        self.ExecuteLLM = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/ExecuteLLM',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExecuteLLMRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExecuteLLMResponse.FromString,
                _registered_method=True)
        self.GetTenantLangfuseCredentials = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/GetTenantLangfuseCredentials',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantLangfuseCredentialsRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantLangfuseCredentialsResponse.FromString,
                _registered_method=True)
        self.SetTenantLangfuseCredentials = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/SetTenantLangfuseCredentials',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetTenantLangfuseCredentialsRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetTenantLangfuseCredentialsResponse.FromString,
                _registered_method=True)
        self.DeleteTenantLangfuseCredentials = channel.unary_unary(
                '/gibson.tenant.v1.TenantService/DeleteTenantLangfuseCredentials',
                request_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteTenantLangfuseCredentialsRequest.SerializeToString,
                response_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteTenantLangfuseCredentialsResponse.FromString,
                _registered_method=True)


class TenantServiceServicer(object):
    """TenantService provides customer-callable tenant-management operations.
    ---------------------------------------------------------------------------
    Agent identities
    ---------------------------------------------------------------------------
    """

    def CreateAgentIdentity(self, request, context):
        """CreateAgentIdentity provisions a new machine identity for an agent, tool,
        or plugin. Returns a one-time client_secret that cannot be recovered after
        this call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgentIdentities(self, request, context):
        """ListAgentIdentities returns all agent/tool/plugin identities provisioned in
        the caller's tenant, with optional kind filtering and pagination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAgentIdentity(self, request, context):
        """RevokeAgentIdentity permanently revokes a machine identity. Existing JWTs
        stop validating within the IdP token TTL (<=60 seconds). Idempotent on
        already-revoked principals (returns NotFound).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOnboardingState(self, request, context):
        """---------------------------------------------------------------------------
        Onboarding
        ---------------------------------------------------------------------------

        GetOnboardingState queries the onboarding progress for a tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOnboardingState(self, request, context):
        """UpdateOnboardingState advances or modifies the onboarding state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantQuota(self, request, context):
        """---------------------------------------------------------------------------
        Quota / usage
        ---------------------------------------------------------------------------

        GetTenantQuota retrieves the configured resource quotas (limits) for a
        tenant. Returns zero values for any quota not explicitly set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantQuotaUsage(self, request, context):
        """GetTenantQuotaUsage returns the live counter values (current usage) from
        Redis. Cheap (single MGET); does not consult Postgres. Use alongside
        GetTenantQuota to render in-app usage UX.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuditEvents(self, request, context):
        """---------------------------------------------------------------------------
        Audit + findings
        ---------------------------------------------------------------------------

        ListAuditEvents returns audit events for a tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportFindings(self, request, context):
        """ExportFindings exports findings to the requested format (json, csv, sarif).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveMissionDraft(self, request, context):
        """---------------------------------------------------------------------------
        Mission drafts
        ---------------------------------------------------------------------------

        SaveMissionDraft persists a mission CUE draft for later use.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMissionDrafts(self, request, context):
        """ListMissionDrafts returns all saved mission drafts for a tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMissionDraft(self, request, context):
        """GetMissionDraft retrieves a single saved draft, including its CUE source
        content (which ListMissionDrafts deliberately omits).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMissionDraft(self, request, context):
        """DeleteMissionDraft removes a saved draft. Idempotent: deleting a missing
        draft returns OK.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviders(self, request, context):
        """---------------------------------------------------------------------------
        LLM providers — tenant CRUD operations
        ---------------------------------------------------------------------------

        ListProviders returns all provider configs for the calling tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProvider(self, request, context):
        """GetProvider returns a single provider config by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProvider(self, request, context):
        """CreateProvider encrypts and stores a new provider config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProvider(self, request, context):
        """UpdateProvider replaces an existing provider config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProvider(self, request, context):
        """DeleteProvider removes a provider config from the store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestProvider(self, request, context):
        """TestProvider validates a proposed provider config by making a minimal live
        request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedProviders(self, request, context):
        """GetSupportedProviders returns the daemon's static catalogue of LLM
        provider types with their per-provider credential field schemas.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviderModels(self, request, context):
        """ListProviderModels fetches the live model catalogue for an already-
        configured provider, looked up by name. Credentials are read from the
        encrypted store; the caller does not pass them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProviderHealth(self, request, context):
        """GetProviderHealth returns the last-known health status of a stored provider.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefaultProvider(self, request, context):
        """GetDefaultProvider returns the tenant's currently configured default
        provider.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultProvider(self, request, context):
        """SetDefaultProvider designates an existing stored provider as the default.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteLLM(self, request, context):
        """---------------------------------------------------------------------------
        LLM execution
        ---------------------------------------------------------------------------

        ExecuteLLM proxies a single (non-streaming) LLM completion.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTenantLangfuseCredentials(self, request, context):
        """---------------------------------------------------------------------------
        Observability — Langfuse credentials
        ---------------------------------------------------------------------------

        GetTenantLangfuseCredentials retrieves the Langfuse project credentials for
        a tenant. Returns NOT_FOUND if no credentials have been configured.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTenantLangfuseCredentials(self, request, context):
        """SetTenantLangfuseCredentials stores or updates Langfuse project credentials
        for a tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTenantLangfuseCredentials(self, request, context):
        """DeleteTenantLangfuseCredentials removes the Langfuse project credentials for
        a tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TenantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAgentIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgentIdentity,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateAgentIdentityRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateAgentIdentityResponse.SerializeToString,
            ),
            'ListAgentIdentities': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgentIdentities,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAgentIdentitiesRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAgentIdentitiesResponse.SerializeToString,
            ),
            'RevokeAgentIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAgentIdentity,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.RevokeAgentIdentityRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.RevokeAgentIdentityResponse.SerializeToString,
            ),
            'GetOnboardingState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOnboardingState,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetOnboardingStateRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetOnboardingStateResponse.SerializeToString,
            ),
            'UpdateOnboardingState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOnboardingState,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateOnboardingStateRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateOnboardingStateResponse.SerializeToString,
            ),
            'GetTenantQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantQuota,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaResponse.SerializeToString,
            ),
            'GetTenantQuotaUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantQuotaUsage,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaUsageRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaUsageResponse.SerializeToString,
            ),
            'ListAuditEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuditEvents,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAuditEventsRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAuditEventsResponse.SerializeToString,
            ),
            'ExportFindings': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportFindings,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExportFindingsRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExportFindingsResponse.SerializeToString,
            ),
            'SaveMissionDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMissionDraft,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SaveMissionDraftRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SaveMissionDraftResponse.SerializeToString,
            ),
            'ListMissionDrafts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMissionDrafts,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListMissionDraftsRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListMissionDraftsResponse.SerializeToString,
            ),
            'GetMissionDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMissionDraft,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetMissionDraftRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetMissionDraftResponse.SerializeToString,
            ),
            'DeleteMissionDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMissionDraft,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteMissionDraftRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteMissionDraftResponse.SerializeToString,
            ),
            'ListProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviders,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProvidersRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProvidersResponse.SerializeToString,
            ),
            'GetProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProvider,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderResponse.SerializeToString,
            ),
            'CreateProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProvider,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateProviderRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateProviderResponse.SerializeToString,
            ),
            'UpdateProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProvider,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateProviderRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateProviderResponse.SerializeToString,
            ),
            'DeleteProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProvider,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteProviderRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteProviderResponse.SerializeToString,
            ),
            'TestProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.TestProvider,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.TestProviderRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.TestProviderResponse.SerializeToString,
            ),
            'GetSupportedProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedProviders,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetSupportedProvidersRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetSupportedProvidersResponse.SerializeToString,
            ),
            'ListProviderModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviderModels,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProviderModelsRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProviderModelsResponse.SerializeToString,
            ),
            'GetProviderHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProviderHealth,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderHealthRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderHealthResponse.SerializeToString,
            ),
            'GetDefaultProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefaultProvider,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetDefaultProviderRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetDefaultProviderResponse.SerializeToString,
            ),
            'SetDefaultProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultProvider,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetDefaultProviderRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetDefaultProviderResponse.SerializeToString,
            ),
            'ExecuteLLM': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteLLM,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExecuteLLMRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExecuteLLMResponse.SerializeToString,
            ),
            'GetTenantLangfuseCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTenantLangfuseCredentials,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantLangfuseCredentialsRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantLangfuseCredentialsResponse.SerializeToString,
            ),
            'SetTenantLangfuseCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTenantLangfuseCredentials,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetTenantLangfuseCredentialsRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetTenantLangfuseCredentialsResponse.SerializeToString,
            ),
            'DeleteTenantLangfuseCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTenantLangfuseCredentials,
                    request_deserializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteTenantLangfuseCredentialsRequest.FromString,
                    response_serializer=gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteTenantLangfuseCredentialsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gibson.tenant.v1.TenantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gibson.tenant.v1.TenantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TenantService(object):
    """TenantService provides customer-callable tenant-management operations.
    ---------------------------------------------------------------------------
    Agent identities
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def CreateAgentIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/CreateAgentIdentity',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateAgentIdentityRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateAgentIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgentIdentities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/ListAgentIdentities',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAgentIdentitiesRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAgentIdentitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAgentIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/RevokeAgentIdentity',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.RevokeAgentIdentityRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.RevokeAgentIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOnboardingState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/GetOnboardingState',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetOnboardingStateRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetOnboardingStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOnboardingState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/UpdateOnboardingState',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateOnboardingStateRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateOnboardingStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenantQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/GetTenantQuota',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenantQuotaUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/GetTenantQuotaUsage',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaUsageRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantQuotaUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuditEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/ListAuditEvents',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAuditEventsRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListAuditEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportFindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/ExportFindings',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExportFindingsRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExportFindingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveMissionDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/SaveMissionDraft',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.SaveMissionDraftRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.SaveMissionDraftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMissionDrafts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/ListMissionDrafts',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListMissionDraftsRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListMissionDraftsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMissionDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/GetMissionDraft',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetMissionDraftRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetMissionDraftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMissionDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/DeleteMissionDraft',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteMissionDraftRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteMissionDraftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/ListProviders',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProvidersRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/GetProvider',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/CreateProvider',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateProviderRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.CreateProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/UpdateProvider',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateProviderRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.UpdateProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/DeleteProvider',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteProviderRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/TestProvider',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.TestProviderRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.TestProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportedProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/GetSupportedProviders',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetSupportedProvidersRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetSupportedProvidersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviderModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/ListProviderModels',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProviderModelsRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ListProviderModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProviderHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/GetProviderHealth',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderHealthRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetProviderHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDefaultProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/GetDefaultProvider',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetDefaultProviderRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetDefaultProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefaultProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/SetDefaultProvider',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetDefaultProviderRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetDefaultProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/ExecuteLLM',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExecuteLLMRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.ExecuteLLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTenantLangfuseCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/GetTenantLangfuseCredentials',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantLangfuseCredentialsRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.GetTenantLangfuseCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTenantLangfuseCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/SetTenantLangfuseCredentials',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetTenantLangfuseCredentialsRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.SetTenantLangfuseCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTenantLangfuseCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gibson.tenant.v1.TenantService/DeleteTenantLangfuseCredentials',
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteTenantLangfuseCredentialsRequest.SerializeToString,
            gibson_dot_tenant_dot_v1_dot_tenant__pb2.DeleteTenantLangfuseCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
